export const metadata = {
  title: 'LDM Steel | Dashboard',
  description: 'Generated by Next.js',
};

export default function DashboardLayout({ children }: { children: React.ReactNode }) {
  return <main className="min-h-screen bg-white text-neutral-900 antialiased">{children}</main>;
}
